### ISSUE TITLE
Recommended method of installing matplotlib

### ISSUE THREAD

**Issue by andrewfowlie** [michaelhb/superplot#27]
I think we're almost there. I pushed a few minor changes to the code today and have been finalizing the text and ref response.

One minor issue is the way we recommend installation of matplotlib. In the past we recommended pip, partly because the Ubuntu 14 LTS  repos had an old version of matplotlib. Now Ubuntu 16 LTS has matplotlib 1.5 anyway, and pip might mess up gtk support. What should we say?

**Comment by michaelhb** [comment]
I think we should specifically warn that the pip version of matplotlib should be avoided due to this issue, and mention that compatible versions are available in the current ubuntu and mint releases. I'm pretty sure that is also the case with Debian, but we'd want to confirm. 

I'm not sure how we ended up recommending the pip version - probably because I got things working on windows by installing the scipy stack and a binary distro of pygtk, then uninstalling and reinstalling matplotlib with pip. Somehow it was able to build the right module when I did that. But that's pretty convoluted and not relevant to linux - probably not worth outlining in the manual. As long as we specify that matplotlib 1.4 or greater with GTK support is required we should be good.
